version: '3'

services:
  artifactory:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:7.77.14
    container_name: artifactory-oss
    environment:
      - ARTIFACTORY_HOME=/var/opt/jfrog/artifactory
    ports:
      - "8081:8081"  # Puerto para la integración con Jenkins
      - "8082:8082"  # Puerto para el portal web de Artifactory
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory

volumes:
  artifactory_data:
